#!/bin/sh
if [ -z "${INPUT_LIB}" ];
then
  INPUT_LIB="input_uvc.so"
fi

if [ -z "${OUTPUT_LIB}" ];
then
  OUTPUT_LIB="output_http.so"
fi

if [ -z "${RESOLUTION}" ];
then
  RESOLUTION="1280x720"
fi

if [ -z "${FPS}" ];
then
  FPS="30"
fi

/usr/local/bin/mjpg_streamer -i "${INPUT_LIB} -r ${RESOLUTION} -d /dev/video0 -f ${FPS}" -o "${OUTPUT_LIB} -p 8080 -l 0.0.0.0 -w /usr/local/share/mjpg-streamer/www"
